import { GameQuestion, GameType } from "@/types/room";

// ========== チューニングガム（テキスト回答）==========
// みんなが同じ答えを出しそうなお題
export const TUNING_GUM_QUESTIONS: GameQuestion[] = [
  { text: "カレーの具材といえば？", inputType: "text" },
  { text: "夏の風物詩は？", inputType: "text" },
  { text: "赤い食べ物といえば？", inputType: "text" },
  { text: "朝食の定番メニューは？", inputType: "text" },
  { text: "お正月に食べるものといえば？", inputType: "text" },
  { text: "コンビニで買うものといえば？", inputType: "text" },
  { text: "動物園の人気者といえば？", inputType: "text" },
  { text: "冬に食べたいものといえば？", inputType: "text" },
  { text: "日本の有名な山といえば？", inputType: "text" },
  { text: "遠足のおやつといえば？", inputType: "text" },
  { text: "ラーメンのトッピングといえば？", inputType: "text" },
  { text: "お花見に持っていくものといえば？", inputType: "text" },
  { text: "黄色いものといえば？", inputType: "text" },
  { text: "丸いものといえば？", inputType: "text" },
  { text: "お祭りの屋台グルメといえば？", inputType: "text" },
  { text: "「ありがとう」を言いたい人は？（関係性で）", inputType: "text" },
  { text: "白い動物といえば？", inputType: "text" },
  { text: "夏休みの宿題といえば？", inputType: "text" },
  { text: "お寿司のネタといえば？", inputType: "text" },
  { text: "学校の教科で一番好きなのは？", inputType: "text" },
  { text: "旅行に行きたい国は？", inputType: "text" },
  { text: "おにぎりの具といえば？", inputType: "text" },
  { text: "スポーツといえば？", inputType: "text" },
  { text: "お弁当のおかずといえば？", inputType: "text" },
  { text: "甘いお菓子といえば？", inputType: "text" },
  { text: "緑色の野菜といえば？", inputType: "text" },
  { text: "日本のお土産といえば？", inputType: "text" },
  { text: "居酒屋の定番メニューは？", inputType: "text" },
  { text: "有名なディズニーキャラクターは？", inputType: "text" },
  { text: "ドラえもんの道具といえば？", inputType: "text" },
  { text: "海のレジャーといえば？", inputType: "text" },
  { text: "温かい飲み物といえば？", inputType: "text" },
  { text: "冷たい飲み物といえば？", inputType: "text" },
  { text: "文房具といえば？", inputType: "text" },
  { text: "クリスマスに食べるものといえば？", inputType: "text" },
  { text: "回転寿司で最初に取るネタは？", inputType: "text" },
  { text: "ピザのトッピングといえば？", inputType: "text" },
  { text: "日本の有名な観光地は？", inputType: "text" },
  { text: "楽器といえば？", inputType: "text" },
  { text: "運動会の競技といえば？", inputType: "text" },
  { text: "犬の名前といえば？", inputType: "text" },
  { text: "猫の名前といえば？", inputType: "text" },
  { text: "ファストフード店といえば？", inputType: "text" },
  { text: "夏に飲みたいものは？", inputType: "text" },
  { text: "誕生日プレゼントといえば？", inputType: "text" },
  { text: "日曜日の朝にすることは？", inputType: "text" },
  { text: "テーマパークといえば？", inputType: "text" },
  { text: "お好み焼きに入れる具は？", inputType: "text" },
  { text: "サラダに入れる野菜は？", inputType: "text" },
  { text: "鍋の具材といえば？", inputType: "text" },
  { text: "パンの種類といえば？", inputType: "text" },
  { text: "映画のジャンルといえば？", inputType: "text" },
  { text: "花の種類といえば？", inputType: "text" },
  { text: "虫といえば？", inputType: "text" },
  { text: "魚といえば？", inputType: "text" },
  { text: "果物といえば？", inputType: "text" },
  { text: "野菜といえば？", inputType: "text" },
  { text: "色といえば？", inputType: "text" },
  { text: "都道府県といえば？", inputType: "text" },
  { text: "季節の行事といえば？", inputType: "text" },
  { text: "おでんの具といえば？", inputType: "text" },
  { text: "ハンバーガーに入っているものは？", inputType: "text" },
  { text: "お風呂に持っていくものは？", inputType: "text" },
  { text: "アイスクリームの味といえば？", inputType: "text" },
  { text: "100円ショップで買うものは？", inputType: "text" },
  { text: "スーパーで最初に行くコーナーは？", inputType: "text" },
  { text: "ケーキの種類といえば？", inputType: "text" },
  { text: "和菓子といえば？", inputType: "text" },
  { text: "朝起きて最初にすることは？", inputType: "text" },
  { text: "寝る前にすることは？", inputType: "text" },
  { text: "雨の日にすることは？", inputType: "text" },
  { text: "カラオケの定番曲といえば？", inputType: "text" },
  { text: "有名なアニメといえば？", inputType: "text" },
  { text: "学校にあるものといえば？", inputType: "text" },
  { text: "公園にあるものといえば？", inputType: "text" },
  { text: "キャンプですることといえば？", inputType: "text" },
  { text: "冬のスポーツといえば？", inputType: "text" },
  { text: "お正月にすることといえば？", inputType: "text" },
  { text: "ハロウィンの仮装といえば？", inputType: "text" },
  { text: "バレンタインにあげるものは？", inputType: "text" },
  { text: "焼き肉で最初に焼くものは？", inputType: "text" },
  { text: "味噌汁の具といえば？", inputType: "text" },
  { text: "チャーハンの具といえば？", inputType: "text" },
  { text: "サンドイッチの中身といえば？", inputType: "text" },
  { text: "自動販売機の飲み物といえば？", inputType: "text" },
  { text: "有名人に会えるならば誰？（職業で）", inputType: "text" },
  { text: "無人島に持っていくものは？", inputType: "text" },
  { text: "宝くじが当たったら買うものは？", inputType: "text" },
  { text: "子供のころの遊びといえば？", inputType: "text" },
  { text: "家電製品といえば？", inputType: "text" },
  { text: "駄菓子といえば？", inputType: "text" },
  { text: "お弁当の主食といえば？", inputType: "text" },
  { text: "乗り物といえば？", inputType: "text" },
  { text: "秋の味覚といえば？", inputType: "text" },
  { text: "春に連想するものは？", inputType: "text" },
  { text: "年末年始のテレビ番組といえば？", inputType: "text" },
  { text: "一番好きなおにぎりの形は？", inputType: "text" },
  { text: "ジブリ映画といえば？", inputType: "text" },
  { text: "休日の過ごし方といえば？", inputType: "text" },
];

// ========== いい線行きましょう（数値回答）==========
// 推理・推測系のお題
export const GOOD_LINE_QUESTIONS: GameQuestion[] = [
  { text: "日本にあるコンビニの数は？", inputType: "number" },
  { text: "東京タワーの高さは何メートル？", inputType: "number" },
  { text: "日本の人口は何万人？", inputType: "number" },
  { text: "富士山の高さは何メートル？", inputType: "number" },
  { text: "1年は何時間？", inputType: "number" },
  { text: "地球から月までの距離は何キロ？", inputType: "number" },
  { text: "サッカーのワールドカップ出場チーム数は？", inputType: "number" },
  { text: "お札（一万円札）の横の長さは何ミリ？", inputType: "number" },
  { text: "東京ドームの収容人数は？", inputType: "number" },
  { text: "新幹線の最高速度は時速何キロ？", inputType: "number" },
  { text: "人間の骨の数は？", inputType: "number" },
  { text: "太陽系の惑星の数は？", inputType: "number" },
  { text: "日本の都道府県の数は？", inputType: "number" },
  { text: "オリンピックの競技数はいくつ？", inputType: "number" },
  { text: "日本の祝日は年間何日？", inputType: "number" },
  { text: "日本一長い川の長さは何キロ？", inputType: "number" },
  { text: "東京スカイツリーの高さは何メートル？", inputType: "number" },
  { text: "地球の赤道の周囲は何キロ？", inputType: "number" },
  { text: "日本の小学校の数は？", inputType: "number" },
  { text: "ジャンボジェット機の座席数は？", inputType: "number" },
  { text: "ひらがなの文字数は？", inputType: "number" },
  { text: "トランプのカードは何枚？（ジョーカー除く）", inputType: "number" },
  { text: "日本の国土面積は何万平方キロ？", inputType: "number" },
  { text: "ピアノの鍵盤の数は？", inputType: "number" },
  { text: "将棋の駒の数は？（両方合わせて）", inputType: "number" },
  { text: "世界の国の数は？", inputType: "number" },
  { text: "1年で日本に来る外国人観光客は何万人？", inputType: "number" },
  { text: "人間の歯の数は？", inputType: "number" },
  { text: "東京から大阪まで新幹線で何分？", inputType: "number" },
  { text: "マラソンの距離は何キロ？", inputType: "number" },
  { text: "サッカーのコートの長さは何メートル？", inputType: "number" },
  { text: "日本で一番深い湖の深さは何メートル？", inputType: "number" },
  { text: "100メートル走の世界記録は何秒？（小数点1桁）", inputType: "number" },
  { text: "日本の平均寿命は何歳？", inputType: "number" },
  { text: "東京23区はいくつ？（ひっかけ）", inputType: "number" },
  { text: "地球の直径は何キロ？", inputType: "number" },
  { text: "1キロは何歩くらい？", inputType: "number" },
  { text: "大相撲の力士の定員は何人？", inputType: "number" },
  { text: "甲子園球場の収容人数は？", inputType: "number" },
  { text: "日本の駅の数は？", inputType: "number" },
  { text: "世界の海の面積は地球の何パーセント？", inputType: "number" },
  { text: "日本の大学の数は？", inputType: "number" },
  { text: "チーターの最高速度は時速何キロ？", inputType: "number" },
  { text: "キリンの首の骨の数は？", inputType: "number" },
  { text: "人間の血管の総延長は何万キロ？", inputType: "number" },
  { text: "日本のスタバの店舗数は？", inputType: "number" },
  { text: "エベレストの高さは何メートル？", inputType: "number" },
  { text: "光の速度は秒速何万キロ？", inputType: "number" },
  { text: "日本の島の数は？", inputType: "number" },
  { text: "世界一高いビルの高さは何メートル？", inputType: "number" },
  { text: "琵琶湖の面積は何平方キロ？", inputType: "number" },
  { text: "東京ディズニーランドの年間来場者数は何万人？", inputType: "number" },
  { text: "国際宇宙ステーションの高度は何キロ？", inputType: "number" },
  { text: "人間の脳の重さは何グラム？", inputType: "number" },
  { text: "日本で一番長いトンネルは何キロ？", inputType: "number" },
  { text: "ナイル川の長さは何キロ？", inputType: "number" },
  { text: "野球のボールの縫い目の数は？", inputType: "number" },
  { text: "成人の体温は平均何度？（小数点1桁）", inputType: "number" },
  { text: "日本のマクドナルドの店舗数は？", inputType: "number" },
  { text: "お年玉の平均額は何円？（小学生）", inputType: "number" },
  { text: "日本人の平均年収は何万円？", inputType: "number" },
  { text: "東京の平均家賃は何万円？（1K）", inputType: "number" },
  { text: "日本で一年間に消費される米の量は何万トン？", inputType: "number" },
  { text: "地球から太陽までの距離は何億キロ？", inputType: "number" },
  { text: "日本の郵便ポストの数は？", inputType: "number" },
  { text: "東京都の人口は何万人？", inputType: "number" },
  { text: "日本の鉄道の総延長は何キロ？", inputType: "number" },
  { text: "ゾウの体重は何トン？", inputType: "number" },
  { text: "日本の信号機の数は何万基？", inputType: "number" },
  { text: "タイタニック号の全長は何メートル？", inputType: "number" },
  { text: "アマゾン川の長さは何キロ？", inputType: "number" },
  { text: "日本の国会議員の数は？（衆参合計）", inputType: "number" },
  { text: "世界一速い電車の最高速度は時速何キロ？", inputType: "number" },
  { text: "バスケットボールのリングの高さは何メートル？", inputType: "number" },
  { text: "卓球台の長さは何センチ？", inputType: "number" },
  { text: "国連の加盟国数は？", inputType: "number" },
  { text: "日本一高い山と二番目の差は何メートル？", inputType: "number" },
  { text: "一円玉の重さは何グラム？", inputType: "number" },
  { text: "日本の自動販売機の数は何万台？", inputType: "number" },
  { text: "人間の心臓は1日に何回拍動する？", inputType: "number" },
  { text: "スカイダイビングの落下速度は時速何キロ？", inputType: "number" },
  { text: "日本最大の湖・琵琶湖の周囲は何キロ？", inputType: "number" },
  { text: "日本の温泉地の数は？", inputType: "number" },
  { text: "日本人が一生で食べるお米の量は何トン？", inputType: "number" },
  { text: "東京から福岡まで飛行機で何分？", inputType: "number" },
  { text: "日本の消防署の数は？", inputType: "number" },
  { text: "シロナガスクジラの体長は何メートル？", inputType: "number" },
  { text: "日本の年間降水量は何ミリ？", inputType: "number" },
  { text: "人間の体の水分は何パーセント？", inputType: "number" },
  { text: "富士山の登山者数は年間何万人？", inputType: "number" },
  { text: "日本で一日に生まれる赤ちゃんの数は？", inputType: "number" },
  { text: "通天閣の高さは何メートル？", inputType: "number" },
  { text: "日本の映画館の数は？", inputType: "number" },
  { text: "テニスコートの長さは何メートル？", inputType: "number" },
  { text: "日本の橋の数は何万本？", inputType: "number" },
  { text: "日本の年間カレー消費量は何億食？", inputType: "number" },
  { text: "月の直径は何キロ？", inputType: "number" },
  { text: "日本の幼稚園・保育園の数は？", inputType: "number" },
  { text: "人間の髪の毛の本数は？", inputType: "number" },
];

// ========== みんなのイーブン（選択回答）==========
// 意見が割れそうな二択＋Even
const EVEN_OPTIONS = ["Yes", "No", "Even"];

export const EVENS_QUESTIONS: GameQuestion[] = [
  { text: "朝食はパン派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "カラオケは好き？", inputType: "select", options: EVEN_OPTIONS },
  { text: "犬と猫なら犬派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "夏と冬なら夏派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "インドア派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "朝型？", inputType: "select", options: EVEN_OPTIONS },
  { text: "甘いものが好き？", inputType: "select", options: EVEN_OPTIONS },
  { text: "辛い食べ物は得意？", inputType: "select", options: EVEN_OPTIONS },
  { text: "海より山が好き？", inputType: "select", options: EVEN_OPTIONS },
  { text: "一人旅が好き？", inputType: "select", options: EVEN_OPTIONS },
  { text: "映画館で映画を見る派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "お化け屋敷に入れる？", inputType: "select", options: EVEN_OPTIONS },
  { text: "納豆は好き？", inputType: "select", options: EVEN_OPTIONS },
  { text: "電話よりLINE派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "料理をするのが好き？", inputType: "select", options: EVEN_OPTIONS },
  { text: "温泉が好き？", inputType: "select", options: EVEN_OPTIONS },
  { text: "寝る時は真っ暗派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "ラーメンはこってり派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "きのこの山派？（たけのこの里ではなく）", inputType: "select", options: EVEN_OPTIONS },
  { text: "遊園地のジェットコースターに乗れる？", inputType: "select", options: EVEN_OPTIONS },
  { text: "目玉焼きには醤油？", inputType: "select", options: EVEN_OPTIONS },
  { text: "読書が好き？", inputType: "select", options: EVEN_OPTIONS },
  { text: "運動が得意？", inputType: "select", options: EVEN_OPTIONS },
  { text: "方向音痴？", inputType: "select", options: EVEN_OPTIONS },
  { text: "虫が触れる？", inputType: "select", options: EVEN_OPTIONS },
  { text: "飛行機より新幹線派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "うどんよりそば派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "肉より魚が好き？", inputType: "select", options: EVEN_OPTIONS },
  { text: "雨の日は嫌い？", inputType: "select", options: EVEN_OPTIONS },
  { text: "お寿司は回転寿司派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "テレビよりYouTube派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "写真を撮られるのは好き？", inputType: "select", options: EVEN_OPTIONS },
  { text: "人前で話すのが得意？", inputType: "select", options: EVEN_OPTIONS },
  { text: "日記をつけている？", inputType: "select", options: EVEN_OPTIONS },
  { text: "カフェよりファミレス派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "ビールは好き？", inputType: "select", options: EVEN_OPTIONS },
  { text: "冬はこたつ派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "観葉植物を育てている？", inputType: "select", options: EVEN_OPTIONS },
  { text: "SNSを毎日チェックする？", inputType: "select", options: EVEN_OPTIONS },
  { text: "映画のエンドロールは最後まで見る？", inputType: "select", options: EVEN_OPTIONS },
  { text: "漫画が好き？", inputType: "select", options: EVEN_OPTIONS },
  { text: "焼き鳥はタレ派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "占いを気にする？", inputType: "select", options: EVEN_OPTIONS },
  { text: "サプライズが好き？", inputType: "select", options: EVEN_OPTIONS },
  { text: "外食より自炊派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "アウトドアウェディングに憧れる？", inputType: "select", options: EVEN_OPTIONS },
  { text: "早起きは得意？", inputType: "select", options: EVEN_OPTIONS },
  { text: "片付けが得意？", inputType: "select", options: EVEN_OPTIONS },
  { text: "ゲームが好き？", inputType: "select", options: EVEN_OPTIONS },
  { text: "コーヒーはブラック派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "スマホのアラームは一度で起きる？", inputType: "select", options: EVEN_OPTIONS },
  { text: "買い物は計画的？", inputType: "select", options: EVEN_OPTIONS },
  { text: "花火大会に毎年行く？", inputType: "select", options: EVEN_OPTIONS },
  { text: "お化けを信じる？", inputType: "select", options: EVEN_OPTIONS },
  { text: "寿司のシャリは少なめ派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "旅行の計画は細かく立てる派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "ペットを飼いたい？", inputType: "select", options: EVEN_OPTIONS },
  { text: "宝くじを買ったことがある？", inputType: "select", options: EVEN_OPTIONS },
  { text: "カップ麺はよく食べる？", inputType: "select", options: EVEN_OPTIONS },
  { text: "和式より洋式トイレ派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "タクシーをよく使う？", inputType: "select", options: EVEN_OPTIONS },
  { text: "DIYが好き？", inputType: "select", options: EVEN_OPTIONS },
  { text: "マヨネーズは好き？", inputType: "select", options: EVEN_OPTIONS },
  { text: "お祭りが好き？", inputType: "select", options: EVEN_OPTIONS },
  { text: "スポーツ観戦が好き？", inputType: "select", options: EVEN_OPTIONS },
  { text: "映画を見るなら邦画派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "ショッピングは好き？", inputType: "select", options: EVEN_OPTIONS },
  { text: "サウナが好き？", inputType: "select", options: EVEN_OPTIONS },
  { text: "家ではリラックス着で過ごす？", inputType: "select", options: EVEN_OPTIONS },
  { text: "お酒に強い？", inputType: "select", options: EVEN_OPTIONS },
  { text: "音楽を聴きながら作業する？", inputType: "select", options: EVEN_OPTIONS },
  { text: "手帳を使っている？", inputType: "select", options: EVEN_OPTIONS },
  { text: "スーパー銭湯に行く？", inputType: "select", options: EVEN_OPTIONS },
  { text: "初詣に毎年行く？", inputType: "select", options: EVEN_OPTIONS },
  { text: "クリスマスは好き？", inputType: "select", options: EVEN_OPTIONS },
  { text: "海外旅行に行きたい？", inputType: "select", options: EVEN_OPTIONS },
  { text: "パクチーは食べられる？", inputType: "select", options: EVEN_OPTIONS },
  { text: "セルフレジをよく使う？", inputType: "select", options: EVEN_OPTIONS },
  { text: "チョコレートが好き？", inputType: "select", options: EVEN_OPTIONS },
  { text: "電車では座りたい派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "写真加工アプリを使う？", inputType: "select", options: EVEN_OPTIONS },
  { text: "ヘッドホンよりイヤホン派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "コンタクトレンズを使っている？", inputType: "select", options: EVEN_OPTIONS },
  { text: "デスクは整理整頓されている？", inputType: "select", options: EVEN_OPTIONS },
  { text: "キャッシュレス決済派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "推しがいる？", inputType: "select", options: EVEN_OPTIONS },
  { text: "紅茶より緑茶派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "映画は字幕より吹替派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "毎朝ニュースをチェックする？", inputType: "select", options: EVEN_OPTIONS },
  { text: "アニメが好き？", inputType: "select", options: EVEN_OPTIONS },
  { text: "ポイントカードを集めている？", inputType: "select", options: EVEN_OPTIONS },
  { text: "忘れ物が多い？", inputType: "select", options: EVEN_OPTIONS },
  { text: "キャンプに行きたい？", inputType: "select", options: EVEN_OPTIONS },
  { text: "餃子はお店で食べる派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "エレベーターより階段派？", inputType: "select", options: EVEN_OPTIONS },
  { text: "夜食を食べる？", inputType: "select", options: EVEN_OPTIONS },
  { text: "自分は几帳面だと思う？", inputType: "select", options: EVEN_OPTIONS },
  { text: "ジムに通っている？", inputType: "select", options: EVEN_OPTIONS },
  { text: "からあげにレモンをかける？", inputType: "select", options: EVEN_OPTIONS },
  { text: "お笑いが好き？", inputType: "select", options: EVEN_OPTIONS },
];

// ゲームタイプからバンクを取得
export function getQuestionBank(gameType: GameType): GameQuestion[] {
  switch (gameType) {
    case "tuning_gum":
      return TUNING_GUM_QUESTIONS;
    case "good_line":
      return GOOD_LINE_QUESTIONS;
    case "evens":
      return EVENS_QUESTIONS;
    default:
      return [];
  }
}

// チューニングガム用: 重み付きランダムで「流」を選択
// 一流 10%, 二流 35%, 三流 35%, 四流 20%
const TUNING_GRADES = [
  { label: "一流", weight: 0.10 },
  { label: "二流", weight: 0.35 },
  { label: "三流", weight: 0.35 },
  { label: "四流", weight: 0.20 },
];

function pickGrade(): string {
  const r = Math.random();
  let cumulative = 0;
  for (const g of TUNING_GRADES) {
    cumulative += g.weight;
    if (r < cumulative) return g.label;
  }
  return TUNING_GRADES[TUNING_GRADES.length - 1].label;
}

// ランダムにN問選択（Fisher-Yatesシャッフル）
export function pickRandomQuestions(gameType: GameType, count: number): GameQuestion[] {
  const bank = getQuestionBank(gameType);
  const shuffled = [...bank];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  const picked = shuffled.slice(0, Math.min(count, shuffled.length));

  // チューニングガムは「X流」を合成
  if (gameType === "tuning_gum") {
    return picked.map((q) => ({
      ...q,
      text: `${pickGrade()}の${q.text}`,
    }));
  }

  return picked;
}
